modLoader="lowcodefml"
loaderVersion = "[2,)"
authors="LoveTropics"
license="ARR"

[[mods]]
modId="lt"
version="1.0"
displayName="Love Tropics Resources"
description='''Resources for the Love Tropics event'''
