name: Build Mods

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - run: |
          zip -r lt-assets.jar assets/ META-INF/ pack.mcmeta
          zip -r lt-data.jar data/ META-INF/ pack.mcmeta

      - uses: actions/upload-artifact@v2
        with:
          name: lt
          path: |
            lt-assets.jar
            lt-data.jar
